In [ ]:
import numpy as np


In [ ]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [ ]:
print (type(my_list))
print (type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
print(np.array(my_list))

[1 2 3]


In [ ]:
# or from a list of list
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# creating arrays using built-in functions
# Return evenly spaced value within a given interval
# start, stop , step

# arange : specify the step/gap between concecutive elements

print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [ ]:
# generate arrays of zeros and ones

print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Returned evenly spaced numbers over a specified interval
# Start , stop , no. of elements (and not step)
#
# specified  no. of values (num)

print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))


[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [ ]:
# Random number arrays

print(np.random.rand(2))
print(np.random.rand(5,5))

[0.08731955 0.78800206]
[[0.32615094 0.54106782 0.24023518 0.54542293 0.4005545 ]
 [0.71519189 0.83667994 0.58848114 0.29615456 0.28101769]
 [0.70559724 0.42259643 0.05731599 0.74702731 0.45231301]
 [0.17577474 0.049377   0.29247534 0.06679913 0.75115649]
 [0.06377152 0.43190832 0.36417241 0.15197153 0.54671034]]


In [ ]:
# For normal Distribution
print(np.random.randn(2))
print(np.random.randn(5,5))

[-0.51555091 -0.06301549]
[[-0.55937093  0.79669711  0.45607646 -1.04570413 -0.29449133]
 [-0.7875427  -1.00801883 -2.11616844  0.66204133 -0.31489931]
 [-0.7060172   0.84032066 -0.75952485 -0.39050736  0.66186708]
 [-0.11713577 -0.97164688 -1.98064121  0.86024347 -1.00596744]
 [ 2.61790811  0.19121545 -0.87231244 -0.42512567  0.63358874]]


In [ ]:
# Random integers from low (inclusive) to high (exclusive)

print(np.random.randint(1,100))  #Single Random integers between 1 and 100
print(np.random.randint(1,100,10))  # 10 random integers between 1 and 100

36
[38 31 27 36 19 43 45 43 74 66]


In [ ]:
# Seeding for reproductable results

np.random.seed(77)
print(np.random.rand(4))  # 4 random numbers

[0.91910903 0.6421956  0.75371223 0.13931457]


In [ ]:
# sequence random number - unpredictable  - seed -> SAme for the same seed all over the worls at once

In [ ]:
# Sorting

arr = np.arange(25)    # no. from 0 to 24
ranarr = np.random.randint(0,50,10)   # 10 random no. between 0 and 50
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[32 39 44 19 32 36 36 47 14 15]


In [ ]:
# reshape : returns an array containing the same data with neew shape
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# Max , Min abd their index position

print(ranarr.max())
print(ranarr.argmax())

print(ranarr.min())
print(ranarr.argmin( ))

47
7
14
8


In [ ]:
#  Creating dample array
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Bracket indexing and selection - similar to python list

# get values at particular index
print(arr[8])

# get values in a range
print(arr[1:5])

# Get values in a range
print(arr[0:5])

8
[1 2 3 4]
[0 1 2 3 4]


In [ ]:
# Broadcasting

# setting a value with index range (broadcasting )
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [ ]:
# reset array ?

arr =  np.arange(0,11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Important notes on slices

slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [ ]:
# change slice

slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)



# Changes made are also there in our orignal array !
# data is not copied , it is the view of the orignal array !
# This avoids memory Problem

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:
li1 = [1,2,3, 4, 5,6,7,8,9]
sliced_li =li1[0:5]
print(sliced_li)
# sliced_li[:] = 99
print(li1)
print(sliced_li)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5]


In [ ]:
# Conditional selection

arr = np.arange(1,11)
print(arr)

# Check each element of the array against the conditon  arr>4
# each element i sTrue if the correspoding element in
print(arr>4)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]


In [ ]:
# store boolean results in another array
bool_arr = arr>4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [ ]:
#Select only those elements from the arr array where
# the corrsponding element in bool_arr is True
# If Effectively filters out the elements of arr where the condition arr > 4 is
# Truwe
print(arr[bool_arr])

[ 5  6  7  8  9 10]


aaaaaaaaaaaarrrrrrrrrrrrrrraaaaaaaaaaaaaaaaaaaaayyyyyyyyyyyyy

In [ ]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Basic arithmetic
print(arr + arr)
print(arr - arr)
print(arr * arr)

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]


In [ ]:
# this will raise a ewarning on divbision by zeri but not an error !
# it just fill spot by nan
print(arr/0)
print(arr/arr)

[nan inf inf inf inf inf inf inf inf inf inf]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-50-f9b141a1c081>:2: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)
<ipython-input-50-f9b141a1c081>:2: RuntimeWarning: invalid value encountered in divide
  print(arr/0)
<ipython-input-50-f9b141a1c081>:3: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [ ]:
# also a warning (but not error ) relating to infinity
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]


<ipython-input-51-4a5320b6a105>:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [ ]:
print(arr**3)

[   0    1    8   27   64  125  216  343  512  729 1000]


In [ ]:
# universal functions
print(np.sqrt(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.sin(arr))
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


<ipython-input-53-7e8ef198a63a>:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [ ]:
# summary stastics
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.median(arr))
print(np.corrcoef(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.average(arr))







55
0
10
10.0
5.0
1.0
3.1622776601683795
5.0
5.0


In [ ]:
# 2d Arrays
# yhis is 2d array with 3 rows an 4 columns

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
# row and column count
print(arr_2d.shape)
# Sum od all columns for each row
print(arr_2d.sum(axis=0))
# Sum od all rows for each column
print(arr_2d.sum(axis=1))

(3, 3)
[60 75 90]
[ 30  75 120]


ASSIGNMENT


In [ ]:
#1. Create an array of 10 zeros
are = np.zeros(10)
print(are)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#2. create an array of 10 ones
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 3. create an array of ten fives
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#4. create an array of integers from 10-50
arr  = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# 5. create an array of all even integers from 10 to 50

arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# 6. create a 3x3 matrix with value ranging from 0 to 8
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 7. create a 3 x3 identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 8 .use numpy to generate random no. betwwen 0 and 1
print(np.random.rand(1))

[0.83667994]


In [ ]:
# 9. generate array of 25 random 25 numpers
arr = np.random.rand(25)
print(arr)

[0.4964146  0.67356546 0.93930446 0.35401226 0.71195678 0.13115485
 0.33414418 0.34672086 0.54914661 0.09991748 0.41623021 0.26035148
 0.84715927 0.51420117 0.02475884 0.22955234 0.82490318 0.24832847
 0.79215201 0.511191   0.22973667 0.90227905 0.49431534 0.54042068
 0.22135471]


In [ ]:
# 10 create an array of 20 linearly spaced point b/w 0 and 1
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
