<a href="https://colab.research.google.com/github/VIVEKsINGH8509/DATA_ANALYTICS/blob/main/DA_LAB1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# 1. Write a NumPy program to get the numpy version and show numpy build configuration.
print(np.__version__)

1.26.4


In [ ]:
# 2 . Write a NumPy program to get help on the add function.



In [ ]:
# 3 . Write a NumPy program to test whether none of the elements of a given array is zero.
x = np.array([1,2,3,4,0])
y = np.array([0,0,0,0,0,0,0])
print(np.all(x))

False


In [ ]:
# 4 . Write a NumPy program to test whether any of the elements of a given array is non-zero.
print(np.any(x))
print(np.any(y))



True
False


In [ ]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
a = np.array([1, 0, -5, np.nan, np.inf])
print(np.isfinite(a))


[ True  True  True False False]


In [ ]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity.
print(np.isinf(a))


[False False False False  True]


In [ ]:
#  7. Write a NumPy program to test element-wise for NaN of a given array.
print(np.isnan(a))

[False False False  True False]


In [ ]:
# # 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also
# test whether a given number is a scalar type or not.
a = [1+1j ,2 , 3.4, 5, 6]

np.iscomplex(a)


True

In [ ]:
a = [1+1j ,2 , 3.4, 5, 6]
np.isreal(a)

array([False,  True,  True,  True,  True])

In [ ]:
a = [1+1j ,2 , 3.4, 5, 6]
np.isscalar(a)


False

In [ ]:
np.isscalar([1,2,3])

False

In [ ]:
# 9.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given arrays.
x = np.array([1, 7, 13, 105])
y = np.array([1, 7, 303, 105])
print(np.equal(x,y))
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True  True False  True]
[False False False False]
[ True  True False  True]
[False False  True False]
[ True  True  True  True]


In [ ]:
# 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the
# memory occupied by the array.
x = np.array([1, 7, 13, 105])
print(x.size)
print(x.nbytes)

4
32


In [ ]:
# 11 . Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# 12. Write a NumPy program to create an array of the integers from 30 to70.
np.arange(30,70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [ ]:
# 13 . Write a NumPy program to create an array of all the even integers from 30 to 70.
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [ ]:
# 14. Write a NumPy program to create a 3x3 identity matrix.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 15 . Write a NumPy program to generate a random number between 0 and 1.
np.random.rand(1)

array([0.39129396])

In [ ]:
# 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
np.random.rand(15)

array([0.93522272, 0.21757907, 0.99869955, 0.68505089, 0.9176016 ,
       0.69401331, 0.4640709 , 0.86560509, 0.72133576, 0.98310728,
       0.31018747, 0.84021828, 0.35239159, 0.36270196, 0.98649489])

In [ ]:
# 17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
# except the first and last.
x = np.arange(15, 56)
x[1: -1]    #x[inclusive: exclusive]


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
print(a1D)
print(a2D)
print(a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 18. Write a NumPy program to create a 3X4 array.
np.random.randint(80,100,(3,4))

array([[84, 94, 95, 92],
       [82, 84, 88, 96],
       [94, 97, 81, 86]])

In [ ]:
# 19 . Write a NumPy program to create a vector of length 10 with values evenly distributed
# between 5 and 50.

np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [ ]:
# 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
# numbers in the range from 9 to 15.
x = np.arange(0, 21)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
sliced_arr = x[9: 16]
sliced_arr

array([ 9, 10, 11, 12, 13, 14, 15])

In [ ]:
sliced_arr[:] = -(sliced_arr[:])
print(sliced_arr)

[ -9 -10 -11 -12 -13 -14 -15]


In [ ]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [ ]:
# 21 Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
np.random.randint(0,10,5)

array([0, 4, 8, 4, 9])

In [ ]:
# 22 . Write a NumPy program to multiply the values of two given vectors.
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,6,5])
np.multiply(x,y)
print(x*y)

[ 9 16 21 24 25]


In [ ]:
#  23 . Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
z = np.random.randint(10,21,(3,4))
print(z)

[[13 11 14 17]
 [10 13 11 11]
 [11 18 20 11]]


In [ ]:
# 24 . Write a NumPy program to find the number of rows and columns of a given matrix.
np.shape(z)


(3, 4)

In [ ]:
# 25 . Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)*3

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [ ]:
# 26 . Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
# equal to 1, and inside 0.

a = np.random.randint(0,100,(10,10))
a[1:-1, 1:-1] = 0
print(a)

[[42 30 84  0 96 13  5 81 15 63]
 [46  0  0  0  0  0  0  0  0 45]
 [75  0  0  0  0  0  0  0  0 20]
 [76  0  0  0  0  0  0  0  0 93]
 [72  0  0  0  0  0  0  0  0 75]
 [62  0  0  0  0  0  0  0  0 70]
 [61  0  0  0  0  0  0  0  0  7]
 [82  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0 95]
 [37 95 41 12 63  5 78 44 57 36]]


In [ ]:
a[0:1] = 1
print(a)

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  0  0  0  0  0  0  0  0 45]
 [ 1  0  0  0  0  0  0  0  0 20]
 [ 1  0  0  0  0  0  0  0  0 93]
 [ 1  0  0  0  0  0  0  0  0 75]
 [ 1  0  0  0  0  0  0  0  0 70]
 [ 1  0  0  0  0  0  0  0  0  7]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0 95]
 [ 1 95 41 12 63  5 78 44 57 36]]


In [ ]:
a[:,0:1] = 1
a

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 45],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 20],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 93],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 75],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 70],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  7],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 95],
       [ 1, 95, 41, 12, 63,  5, 78, 44, 57, 36]])

In [ ]:
a[-1:] = 1
a

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 45],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 20],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 93],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 75],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 70],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  7],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0, 95],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [ ]:
a[:, -1:] = 1
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
#27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
#3, 4, 5.

a = np.diag([1, 2, 3, 4, 5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
np.random.randint(1, 20,(3,3,3))

array([[[ 2, 13,  8],
        [15,  9, 18],
        [15,  9,  1]],

       [[16, 16, 14],
        [ 5,  2, 17],
        [ 5, 18,  3]],

       [[16, 16, 13],
        [ 7,  6, 16],
        [17,  1,  9]]])

In [ ]:
#29. Write a NumPy program to compute the inner product of two given vectors.
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,6,5])
np.dot(x, y)


95

In [ ]:
# 30. Write a NumPy program to sort a given array by row and column in ascending order.
x = np.array([[10, 7, 56, 8, 96, 69, 6, 55], [2, 5, 9, 3, 4, 0, 89, 68]])              #square brackets are important while creating n -dim array
x

array([[10,  7, 56,  8, 96, 69,  6, 55],
       [ 2,  5,  9,  3,  4,  0, 89, 68]])

In [ ]:
x.sort()
x

array([[ 6,  7,  8, 10, 55, 56, 69, 96],
       [ 0,  2,  3,  4,  5,  9, 68, 89]])

In [ ]:
# 31. Write a NumPy program to extract all numbers from a given array which are less and greater
# than a specified number.

np.extract(x>3,x)


array([ 6,  7,  8, 10, 55, 56, 69, 96,  4,  5,  9, 68, 89])

In [ ]:
# 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
# given number.
z = np.array([ 6,  7,  8, 10, 55, 56, 69, 96,  4,  5,  9, 68, 89])
z = np.where(z==69, 5, z)
z


array([ 6,  7,  8, 10, 55, 56,  5, 96,  4,  5,  9, 68, 89])

In [ ]:
z = np.where(z>69, 1, z)
z

array([ 6,  7,  8, 10, 55, 56,  5,  1,  4,  5,  9, 68,  1])

In [ ]:
z = np.where(z<69, 2, z)
z

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#33. Write a NumPy program to create an array of equal shape and data type of a given array.
x = np.random.randint(10, 100,(2, 2))
print(x.dtype)
print(x)

int64
[[42 46]
 [63 98]]


In [ ]:
#Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a
#variable.
x = np.random.randint(10, 100,(3, 5, 4))
x

array([[[92, 25, 64, 95],
        [28, 56, 22, 60],
        [88, 49, 25, 16],
        [89, 52, 90, 65],
        [60, 42, 53, 48]],

       [[14, 28, 78, 78],
        [26, 33, 28, 54],
        [90, 22, 48, 48],
        [17, 44, 43, 12],
        [28, 66, 32, 29]],

       [[85, 51, 13, 81],
        [83, 22, 48, 76],
        [36, 52, 60, 74],
        [92, 40, 56, 74],
        [97, 53, 26, 81]]])

In [ ]:
#35. Write a NumPy program to multiply two given arrays of same size element-by-element.
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,6,5])
print(x*y)


[ 9 16 21 24 25]
